---
name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.5.3

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v22

      - name: "Check format"
        run: nix develop -c sbt scalafmtCheckAll scalafmtSbtCheck

      - name: "Compile"
        run: nix develop -c sbt compile Test/compile

      - name: "Test"
        run: nix develop -c sbt test
